export const SET_LOADING = "SET_LOADING";

export const REGISTER_ACTION = "REGISTER_ACTION";
export const REGISTER_ACTION_SUCCESS = "REGISTER_ACTION_SUCCESS";
export const REGISTER_ACTION_FAILURE = "REGISTER_ACTION_FAILURE";

export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGIN_ACTION_SUCCESS = "LOGIN_ACTION_SUCCESS";
export const LOGIN_ACTION_FAILURE = "LOGIN_ACTION_FAILURE";

export const LOGOUT_ACTION = "LOGOUT_ACTION";
export const LOGOUT_ACTION_SUCCESS = "LOGOUT_ACTION_SUCCESS";
export const LOGOUT_ACTION_FAILURE = "LOGOUT_ACTION_FAILURE";